services:
  api:
    build:
      context: api
    ports:
      - "3000:3000"

    depends_on:
      - db 
    env_file:
      - api/.env

  db:

    image: redis:alpine
    ports:
      - "6379:6379"

    volumes:
      - .data:/data